# Generated by Django 4.2.13 on 2024-07-10 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_player_team_alter_address_state_and_more'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Summary'),
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight', models.CharField(blank=True, choices=[('Goal', 'Goal'), ('Assist', 'Assist'), ('Save', 'Save'), ('Yellow Card', 'Yellow Card'), ('Red Card', 'Red Card'), ('Penalty', 'Penalty'), ('Free Kick', 'Free Kick'), ('Corner Kick', 'Corner Kick'), ('Throw In', 'Throw In'), ('Goal Kick', 'Goal Kick'), ('Penalty Kick', 'Penalty Kick'), ('Own Goal', 'Own Goal'), ('Hat Trick', 'Hat Trick'), ('Clean Sheet', 'Clean Sheet')], default='Goal', max_length=50, verbose_name='Highlight')),
                ('match', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='matches.match', verbose_name='Match')),
                ('player', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='profiles.player', verbose_name='Player')),
            ],
            options={
                'verbose_name': 'Match Highlight',
                'verbose_name_plural': 'Match Highlights',
            },
        ),
    ]
