# Generated by Django 4.2.13 on 2024-07-30 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('profiles', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(blank=True, limit_choices_to={'home_team': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_matches', to='teams.team', verbose_name='Away Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='highlights',
            field=models.ManyToManyField(blank=True, related_name='matche_highlights', to='matches.highlight', verbose_name='Highlights'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(blank=True, limit_choices_to={'home_team': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_matches', to='teams.team', verbose_name='Home Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='matches.venue', verbose_name='Venue'),
        ),
        migrations.AddField(
            model_name='highlight',
            name='player',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='profiles.player', verbose_name='Player'),
        ),
    ]
