# Generated by Django 4.2.13 on 2024-07-10 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_summary_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='Canceled'),
        ),
        migrations.AddField(
            model_name='match',
            name='is_overtime',
            field=models.BooleanField(default=False, verbose_name='Overtime'),
        ),
        migrations.AddField(
            model_name='match',
            name='is_penalty_shootout',
            field=models.BooleanField(default=False, verbose_name='Penalty Shootout'),
        ),
        migrations.AddField(
            model_name='match',
            name='is_postponed',
            field=models.BooleanField(default=False, verbose_name='Postponed'),
        ),
        migrations.AddField(
            model_name='match',
            name='regulation_time',
            field=models.PositiveIntegerField(default=90, help_text='In minutes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Regulation Time'),
        ),
    ]
