# Generated by Django 4.2.13 on 2024-07-10 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_is_canceled_match_is_overtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='highlights',
            field=models.ManyToManyField(blank=True, related_name='matche_highlights', to='matches.highlight', verbose_name='Highlights'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='match',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='matches.match', verbose_name='Match'),
        ),
    ]
