services:
  docs:
    image: rhs_soccer_local_docs
    container_name: rhs_soccer_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./rhs_soccer:/app/rhs_soccer:z
    ports:
      - '9000:9000'
    command: /start-docs
