volumes:
  rhs_soccer_local_postgres_data: {}
  rhs_soccer_local_postgres_data_backups: {}
  rhs_soccer_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: rhs_soccer_local_django
    container_name: rhs_soccer_local_django
    # depends_on:
    #   - postgres
    #   - redis
    #   - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      #- ./.envs/.production/.django
    ports:
      - '8000:8000'
    command: /start

  # postgres:
  #   build:
  #     context: .
  #     dockerfile: ./compose/production/postgres/Dockerfile
  #   image: rhs_soccer_production_postgres
  #   container_name: rhs_soccer_local_postgres
  #   volumes:
  #     - rhs_soccer_local_postgres_data:/var/lib/postgresql/data
  #     - rhs_soccer_local_postgres_data_backups:/backups
    # env_file:
    #   - ./.envs/.local/.django

  # mailpit:
  #   image: docker.io/axllent/mailpit:latest
  #   container_name: rhs_soccer_local_mailpit
  #   ports:
  #     - "8025:8025"

  # redis:
  #   image: docker.io/redis:6
  #   container_name: rhs_soccer_local_redis
    
  #   volumes:
  #     - rhs_soccer_local_redis_data:/data
    

  # celeryworker:
  #   <<: *django
  #   image: rhs_soccer_local_celeryworker
  #   container_name: rhs_soccer_local_celeryworker
  #   depends_on:
  #     - redis
  #    # - postgres
  #     - mailpit
  #   ports: []
  #   command: /start-celeryworker

  # celerybeat:
  #   <<: *django
  #   image: rhs_soccer_local_celerybeat
  #   container_name: rhs_soccer_local_celerybeat
  #   depends_on:
  #     - redis
  #     #- postgres
  #     - mailpit
  #   ports: []
  #   command: /start-celerybeat

  # flower:
  #   <<: *django
  #   image: rhs_soccer_local_flower
  #   container_name: rhs_soccer_local_flower
  #   ports:
  #     - '5555:5555'
  #   command: /start-flower
