# Generated by Django 4.2.13 on 2024-07-10 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='slug',
        ),
    ]
