# Generated by Django 4.2.13 on 2024-07-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_location_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, unique=True, verbose_name='slug'),
        ),
    ]
