# Generated by Django 4.2.13 on 2024-07-10 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='event',
            field=models.ForeignKey(limit_choices_to={'need_volunteers': True}, on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='events.event', verbose_name='event'),
        ),
    ]
