# Generated by Django 4.2.13 on 2024-07-10 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_faebook_socialmedia_faecbook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='snapchat',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='tiktok',
        ),
    ]
