# Generated by Django 4.2.13 on 2024-07-10 16:19

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_resourcecategory_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Description'),
        ),
    ]
