# Generated by Django 4.2.13 on 2024-07-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_resource_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcecategory',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='resourcecategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
