# Generated by Django 4.2.13 on 2024-07-10 16:26

from django.db import migrations, models
import rhs_soccer.core.enums


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_resourcecategory_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default=rhs_soccer.core.enums.DificultyLevel['EASY'], max_length=255, verbose_name='Difficulty'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
