# Generated by Django 4.2.13 on 2024-07-10 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_campaign_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='player',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='team',
        ),
        migrations.RemoveField(
            model_name='playerfee',
            name='player',
        ),
    ]
