# Generated by Django 4.2.13 on 2024-07-09 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('address2', models.CharField(blank=True, max_length=255, verbose_name='Address 2')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('state', models.CharField(choices=[('Alabama', 'ALABAMA'), ('Alaska', 'ALASKA'), ('Arizona', 'ARIZONA'), ('Arkansas', 'ARKANSAS'), ('California', 'CALIFORNIA'), ('Colorado', 'COLORADO'), ('Connecticut', 'CONNECTICUT'), ('Delaware', 'DELAWARE'), ('Florida', 'FLORIDA'), ('Georgia', 'GEORGIA'), ('Hawaii', 'HAWAII'), ('Idaho', 'IDAHO'), ('Illinois', 'ILLINOIS'), ('Indiana', 'INDIANA'), ('Iowa', 'IOWA'), ('Kansas', 'KANSAS'), ('Kentucky', 'KENTUCKY'), ('Louisiana', 'LOUISIANA'), ('Maine', 'MAINE'), ('Maryland', 'MARYLAND'), ('Massachusetts', 'MASSACHUSETTS'), ('Michigan', 'MICHIGAN'), ('Minnesota', 'MINNESOTA'), ('Mississippi', 'MISSISSIPPI'), ('Missouri', 'MISSOURI'), ('Montana', 'MONTANA'), ('Nebraska', 'NEBRASKA'), ('Nevada', 'NEVADA'), ('New Hampshire', 'NEW_HAMPSHIRE'), ('New Jersey', 'NEW_JERSEY'), ('New Mexico', 'NEW_MEXICO'), ('New York', 'NEW_YORK'), ('North Carolina', 'NORTH_CAROLINA'), ('North Dakota', 'NORTH_DAKOTA'), ('Ohio', 'OHIO'), ('Oklahoma', 'OKLAHOMA'), ('Oregon', 'OREGON'), ('Pennsylvania', 'PENNSYLVANIA'), ('Rhode Island', 'RHODE_ISLAND'), ('South Carolina', 'SOUTH_CAROLINA'), ('South Dakota', 'SOUTH_DAKOTA'), ('Tennessee', 'TENNESSEE'), ('Texas', 'TEXAS'), ('Utah', 'UTAH'), ('Vermont', 'VERMONT'), ('Virginia', 'VIRGINIA'), ('Washington', 'WASHINGTON'), ('West Virginia', 'WEST_VIRGINIA'), ('Wisconsin', 'WISCONSIN'), ('Wyoming', 'WYOMING')], max_length=255, verbose_name='State')),
                ('zip_code', models.CharField(max_length=255, verbose_name='Zip Code')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=255, region=None, verbose_name='Phone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('jeresy_number', models.CharField(blank=True, max_length=10, verbose_name='Jeresy Number')),
                ('grade', models.CharField(blank=True, choices=[('6th Grader', '6th Grader'), ('7th Grader', '7th Grader'), ('8th Grader', '8th Grader'), ('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior')], help_text='Grade', verbose_name='Grade')),
                ('position', models.CharField(blank=True, choices=[('Goalkeeper', 'Goalkeeper'), ('Defender', 'Defender'), ('Midfielder', 'Midfielder'), ('Forward', 'Forward')], max_length=255, verbose_name='Position')),
                ('height', models.CharField(blank=True, max_length=255, verbose_name='Height')),
                ('weight', models.CharField(blank=True, max_length=255, verbose_name='Weight')),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Retired', 'Retired'), ('Transferred', 'Transferred'), ('Resigned', 'Resigned'), ('Suspended', 'Suspended')], help_text='Status', max_length=255, verbose_name='Status')),
                ('bio', tinymce.models.HTMLField(blank=True, verbose_name='Bio')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=50, verbose_name='Emergency Contact Name')),
                ('emergency_contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region=None, verbose_name='Emergency Contact Phone')),
                ('emergency_contact_relationship', models.CharField(blank=True, choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Grandparent', 'Grandparent'), ('Sister', 'Sister'), ('Brother', 'Brother'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Friend', 'Friend'), ('Spouse', 'Spouse'), ('Neighbor', 'Neighbor'), ('Other', 'Other')], default='Other', max_length=50, verbose_name='Emergency Contact Relationship')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents', to='profiles.address')),
                ('players', models.ManyToManyField(blank=True, related_name='parents', to='profiles.player')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('bio', tinymce.models.HTMLField(blank=True, verbose_name='Bio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='profiles.address')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Manager',
                'verbose_name_plural': 'Managers',
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('bio', tinymce.models.HTMLField(blank=True, verbose_name='Bio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaches', to='profiles.address')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Coach',
                'verbose_name_plural': 'Coaches',
            },
        ),
    ]
