# Generated by Django 4.2.13 on 2024-07-30 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='teams.team'),
        ),
        migrations.AddField(
            model_name='parent',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents', to='profiles.address'),
        ),
        migrations.AddField(
            model_name='parent',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='parents', to='profiles.player'),
        ),
        migrations.AddField(
            model_name='parent',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='manager',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='profiles.address'),
        ),
        migrations.AddField(
            model_name='manager',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='coach',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaches', to='profiles.address'),
        ),
        migrations.AddField(
            model_name='coach',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach', to='profiles.profile'),
        ),
    ]
