# Generated by Django 4.2.13 on 2024-07-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('Goalkeeper', 'GOALKEEPER'), ('Defender', 'DEFENDER'), ('Midfielder', 'MIDFIELDER'), ('Forward', 'FORWARD')], max_length=255, verbose_name='Position'),
        ),
    ]
