# Generated by Django 4.2.13 on 2024-07-30 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('wagtailcore', '0093_uploadedfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Subtitle')),
                ('description', wagtail.fields.RichTextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Team Page',
                'verbose_name_plural': 'Team Page',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('home_team', models.BooleanField(default=True, verbose_name='Home Team')),
                ('name', models.CharField(max_length=255, verbose_name='Team Name')),
                ('short_name', models.CharField(blank=True, max_length=255, verbose_name='Team Short Name')),
                ('season', models.CharField(blank=True, choices=[('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028'), ('2028-2029', '2028-2029')], default='2024-2025', help_text='Season', max_length=255, verbose_name='Season')),
                ('description', wagtail.fields.RichTextField(verbose_name='Team Description')),
                ('level', models.CharField(blank=True, choices=[('Varsity', 'Varsity'), ('JV', 'JV'), ('Sophmore', 'Sophmore'), ('Freshman', 'Freshman')], default='Varsity', help_text='Team Level', max_length=255, verbose_name='Team Level')),
                ('assistant_coach', models.ForeignKey(blank=True, limit_choices_to={'role': 'Coach'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_coach', to=settings.AUTH_USER_MODEL, verbose_name='Assistant Coach')),
                ('fundraiser', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='payments.campaign')),
                ('head_coach', models.ForeignKey(blank=True, limit_choices_to={'role': 'Coach'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_coach', to=settings.AUTH_USER_MODEL, verbose_name='Head Coach')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Team Image')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
    ]
