# Generated by Django 4.2.13 on 2024-07-10 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Subtitle')),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Team Page',
                'verbose_name_plural': 'Team Page',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('home_team', models.BooleanField(default=True, verbose_name='Home Team')),
                ('name', models.CharField(max_length=255, verbose_name='Team Name')),
                ('short_name', models.CharField(blank=True, max_length=255, verbose_name='Team Short Name')),
                ('season', models.CharField(blank=True, choices=[('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028'), ('2028-2029', '2028-2029')], default='2024-2025', help_text='Season', max_length=255, verbose_name='Season')),
                ('description', tinymce.models.HTMLField(verbose_name='Team Description')),
                ('level', models.CharField(blank=True, choices=[('Varsity', 'Varsity'), ('JV', 'JV'), ('Sophmore', 'Sophmore'), ('Freshman', 'Freshman')], default='Varsity', help_text='Team Level', max_length=255, verbose_name='Team Level')),
                ('image', models.ImageField(upload_to='teams', verbose_name='Team Image')),
                ('assistant_coach', models.ForeignKey(blank=True, limit_choices_to={'role': 'Coach'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_coach', to=settings.AUTH_USER_MODEL, verbose_name='Assistant Coach')),
                ('head_coach', models.ForeignKey(blank=True, limit_choices_to={'role': 'Coach'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_coach', to=settings.AUTH_USER_MODEL, verbose_name='Head Coach')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
    ]
