# Generated by Django 4.2.13 on 2024-08-01 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='assistant_coach',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Coach'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_coach', to=settings.AUTH_USER_MODEL, verbose_name='Assistant Coach'),
        ),
        migrations.AddField(
            model_name='team',
            name='fundraiser',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='payments.campaign'),
        ),
        migrations.AddField(
            model_name='team',
            name='head_coach',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Coach'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_coach', to=settings.AUTH_USER_MODEL, verbose_name='Head Coach'),
        ),
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Team Image'),
        ),
    ]
