# Generated by Django 4.2.13 on 2024-07-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, upload_to='teams', verbose_name='Team Image'),
        ),
    ]
