# Generated by Django 4.2.13 on 2024-07-10 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_donation_player_remove_donation_team_and_more'),
        ('teams', '0002_alter_team_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='fundraiser',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='payments.campaign'),
        ),
    ]
